version: "3"
services:
  webapp:
    image: thecodingmachine/php:7.2-v2-apache
    ports:
      - "8080:80"
    volumes: 
      - './app_data/web:/var/www/html'
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1
      PHP_INI_XDEBUG__REMOTE_enable: 1
      APACHE_DOCUMENT_ROOT: public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes: 
      - './app_data/database:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: i0mr11t–ºTfuker
    restart: unless-stopped