old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbit'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: true

            #requires php_sockets.dll
            use_socket: true # default false
    rpc_clients:
        tcp_request:
            connection: default
            lazy: true
            direct_reply_to: false
            expect_serialized_response: false
    producers:
        udp_request:
            connection:       default
            exchange_options: {name: 'udp', type: direct}
            queue_options:    {name: 'udp_queue'}